# Generated by Django 4.1.7 on 2023-03-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_about', models.TextField(blank=True)),
                ('service_specialist_photo', models.ImageField(upload_to='photos/specialist/')),
                ('service_create', models.DateTimeField(auto_now_add=True)),
                ('service_update', models.DateTimeField(auto_now=True)),
                ('service_work', models.BooleanField(default=True)),
            ],
        ),
    ]
